version: '3'

shopt: [ -s globstar ]

tasks:
  check:
    cmds:
      - task vulncheck
      - task lint
      - task test

  monitor:
    cmds:
      - while true; do (task lint && task test) || true; echo 'sleeping...'; sleep 15; echo 'go again!';done

  test:
    cmds:
      - go test -race ./...
    sources:
      - ./**/*.go
      - taskfile.yml

  lint:
    cmds:
      - go tool golangci-lint fmt
      - go tool golangci-lint run --output.tab.path stdout --output.tab.print-linter-name --output.tab.colors
    sources:
      - ./**/*.go
      - taskfile.yml
      - .golangci.yml

  vulncheck:
    cmds:
      - go tool govulncheck ./...
    sources:
      - ./**/*.go
      - taskfile.yml

  deps:
    cmds:
      - go get -u ./...
      - go mod tidy
      - go mod vendor
    sources:
      - ./**/*.go
      - go.mod
      - go.sum
      - taskfile.yml
      - .golangci.yml
